# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    # http_client:
    #     default_options:
    #         headers:
    #             'Authorization': 'Bearer %env(CALENDLY_ACCESS_TOKEN)%'
    http_client:
        scoped_clients:
            cal.client:
                #scope: 'https://api\.calendly\.com'
                base_uri: 'https://api.calendly.com'
                headers:
                    Authorization: 'Bearer %env(CALENDLY_ACCESS_TOKEN)%'

                # HTTP Bearer authentication (also called token authentication)
                # auth_bearer: '%env(CALENDLY_ACCESS_TOKEN)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
